services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"
      - "443:3443"
    volumes:
      - /etc/ssl/cloudflare:/etc/ssl/cloudflare:ro
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - env.stage
    volumes:
      - ../backend/models:/app/models:ro
    restart: unless-stopped
